spring:
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host:
    port:
    username:
    password:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

redis:
  datasource:
    host: localhost
    port: 0101

cloud:
  container:
    name: temp

ACCESS_TOKEN_SECRET_KEY: ""
REFRESH_TOKEN_SECRET_KEY: ""