spring:
  datasource:
    url: jdbc:mysql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_USERNAME}
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: ${PROD_MAIL_PORT}
    username: ${PROD_MAIL_USERNAME}
    password: ${PROD_MAIL_SECRET_KEY}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

cloud:
  container:
    name: ${PROD_CLOUD_CONTAINER}


redis:
  datasource:
    host:  ${PROD_REDIS_HOST}
    port: ${PROD_REDIS_PORT}

ACCESS_TOKEN_SECRET_KEY: ${PROD_ACCESS_TOKEN_KEY}
REFRESH_TOKEN_SECRET_KEY: ${PROD_REFRESH_TOKEN_KEY}